version = 1
SPDX-PackageName = "carbonio-message-dispatcher-db"
SPDX-PackageSupplier = "Zextras <packages@zextras.com>"
SPDX-PackageDownloadLocation = "https://github.com/Zextras/carbonio-message-dispatcher-db"

[[annotations]]
path = "CHANGELOG.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Zextras <https://www.zextras.com>"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = "COPYING"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Zextras <https://www.zextras.com>"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = "README.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Zextras <https://www.zextras.com>"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = "yap.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Zextras <https://www.zextras.com>"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = [".github/renovate.json", ".releaserc.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Zextras <https://www.zextras.com>"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = "package/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Zextras <https://www.zextras.com>"
SPDX-License-Identifier = "AGPL-3.0-only"
